language: c++

compiler:
  - clang
  - gcc

os:
  - linux

dist: bionic

notifications:
  email: false

addons:
  apt:
    packages:
      - clang # For clang variant, PATH is reset
      - cmake
      - pkg-config
      - libfmt-dev
      - googletest
      - python3-dev
      - cython3
      - python3-nose

before_install:
# Get libfmt 5, not available in bionic
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/f/fmtlib/libfmt-dev_5.2.1+ds-2_amd64.deb && sudo dpkg -i libfmt-dev_5.2.1+ds-2_amd64.deb

script:
  - |
    set -e
    #pyenv global 3.6.7 # Not working
    echo $PATH
    export PATH=/home/travis/bin:/bin:/usr/bin:/usr/local/bin # Reset path so pyenv is ignored
    mkdir build
    cd build
    cmake ..
    make VERBOSE=1
    ctest -V
    cd ../python
    nosetests3 -v
